[build]
builder = "NIXPACKS"
buildCommand = "cd apps/server && pnpm install --frozen-lockfile && pnpm -r prisma generate && pnpm build"
installCommand = "cd apps/server && pnpm install --frozen-lockfile"

[deploy]
startCommand = "cd apps/server && node dist/server.js"
