[build]
builder = "NIXPACKS"
buildCommand = "npm install -g pnpm@9 --prefix=/usr/local && export PATH=$PATH:/usr/local/bin && cd apps/server && pnpm install --no-frozen-lockfile && pnpm exec prisma generate && pnpm build"
installCommand = "npm install -g pnpm@9 --prefix=/usr/local && export PATH=$PATH:/usr/local/bin && cd apps/server && pnpm install --no-frozen-lockfile"

[deploy]
startCommand = "export PATH=$PATH:/usr/local/bin && cd apps/server && pnpm start"
