[build]
builder = "NIXPACKS"
buildCommand = "npm install -g pnpm@9 --prefix=/usr/local && export PATH=$PATH:/usr/local/bin && pnpm install --no-frozen-lockfile && pnpm --filter @massage-bot/server exec prisma generate && pnpm --filter @massage-bot/server run build"
installCommand = "npm install -g pnpm@9 --prefix=/usr/local && export PATH=$PATH:/usr/local/bin && pnpm install --no-frozen-lockfile"

[deploy]
startCommand = "export PATH=$PATH:/usr/local/bin && pnpm --filter @massage-bot/server run start"
