[build]
builder = "nixpacks"
src = "."
installCommand = "cd apps/server && pnpm install"
buildCommand = "cd apps/server && pnpm prisma generate && cd apps/server && pnpm build"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "cd apps/server && pnpm start"
